[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist/spa"

[build.environment]
  NODE_VERSION = "18"

# SPA redirect rules (this is critical for React/Vite apps)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Form handling
[[redirects]]
  from = "/thank-you"
  to = "/?submitted=true"
  status = 302

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
