[build]
  command = "npm install --legacy-peer-deps && npm run build:client"
  publish = "dist/spa"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
